In [31]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
plt.style.use('ggplot')


from tensorflow.keras.optimizers import Adam,Adagrad
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot  as plt
import pandas as pd 
plt.style.use(['seaborn-white'])

# 텐서플로우

In [32]:
x1_data = [1,0,3,4,5]  #공부한시간
x2_data = [0,1,2,3,4] #출석일수
y_data = [1,2,3,4,5] #점수

In [33]:
x1 = tf.constant( x1_data , tf.float32)
x2 = tf.constant( x2_data , tf.float32)
y = tf.constant( y_data , tf.float32)

In [34]:
tf.random.uniform([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.19647384], dtype=float32)>

In [35]:
w1 = tf.Variable(tf.random.uniform([1])) # x1 의 가중치
w2 = tf.Variable(tf.random.uniform([1])) # x2 의 가중치
b = tf.Variable(tf.random.uniform([1])) 

In [36]:
# cost 구하는 함수
def compute_loss():
    hx = w1*x1 + w2*x2 + b
    cost = tf.reduce_mean( (hx - y)**2 )
    return cost

In [37]:
# 
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list=[w1,w2,b] ) # 미분
    print(i,'cost: ',compute_loss().numpy())

0 cost:  0.0101822745
1 cost:  0.20030208
2 cost:  0.18669292
3 cost:  0.05666151
4 cost:  0.006080593
5 cost:  0.06044385
6 cost:  0.11098258
7 cost:  0.090288915
8 cost:  0.034285527
9 cost:  0.0043794457
10 cost:  0.021282252
11 cost:  0.0531533
12 cost:  0.059411705
13 cost:  0.035835184
14 cost:  0.009245242
15 cost:  0.004161902
16 cost:  0.019462764
17 cost:  0.0335253
18 cost:  0.030136758
19 cost:  0.014226258
20 cost:  0.002647811
21 cost:  0.0050818687
22 cost:  0.015218675
23 cost:  0.019756474
24 cost:  0.013722047
25 cost:  0.0043323166
26 cost:  0.0012570743
27 cost:  0.00588239
28 cost:  0.011008677
29 cost:  0.010120406
30 cost:  0.0045596166
31 cost:  0.0007463837
32 cost:  0.002142779
33 cost:  0.0057364213
34 cost:  0.006495072
35 cost:  0.0035728354
36 cost:  0.00064361515
37 cost:  0.00083114335
38 cost:  0.0030430285
39 cost:  0.003932935
40 cost:  0.0023533343
41 cost:  0.0004271082
42 cost:  0.00038746154
43 cost:  0.0017501414
44 cost:  0.0023462179
45 cost:  

366 cost:  0.0
367 cost:  0.0
368 cost:  0.0
369 cost:  0.0
370 cost:  0.0
371 cost:  0.0
372 cost:  0.0
373 cost:  0.0
374 cost:  0.0
375 cost:  0.0
376 cost:  0.0
377 cost:  0.0
378 cost:  0.0
379 cost:  0.0
380 cost:  0.0
381 cost:  0.0
382 cost:  0.0
383 cost:  0.0
384 cost:  0.0
385 cost:  0.0
386 cost:  0.0
387 cost:  0.0
388 cost:  0.0
389 cost:  0.0
390 cost:  0.0
391 cost:  0.0
392 cost:  0.0
393 cost:  0.0
394 cost:  0.0
395 cost:  0.0
396 cost:  0.0
397 cost:  0.0
398 cost:  0.0
399 cost:  0.0
400 cost:  0.0
401 cost:  0.0
402 cost:  0.0
403 cost:  0.0
404 cost:  0.0
405 cost:  0.0
406 cost:  0.0
407 cost:  0.0
408 cost:  0.0
409 cost:  0.0
410 cost:  0.0
411 cost:  0.0
412 cost:  0.0
413 cost:  0.0
414 cost:  0.0
415 cost:  0.0
416 cost:  0.0
417 cost:  0.0
418 cost:  0.0
419 cost:  0.0
420 cost:  0.0
421 cost:  0.0
422 cost:  0.0
423 cost:  0.0
424 cost:  0.0
425 cost:  0.0
426 cost:  0.0
427 cost:  0.0
428 cost:  0.0
429 cost:  0.0
430 cost:  0.0
431 cost:  0.0
432 cost: 

917 cost:  0.0
918 cost:  0.0
919 cost:  0.0
920 cost:  0.0
921 cost:  0.0
922 cost:  0.0
923 cost:  0.0
924 cost:  0.0
925 cost:  0.0
926 cost:  0.0
927 cost:  0.0
928 cost:  0.0
929 cost:  0.0
930 cost:  0.0
931 cost:  0.0
932 cost:  0.0
933 cost:  0.0
934 cost:  0.0
935 cost:  0.0
936 cost:  0.0
937 cost:  0.0
938 cost:  0.0
939 cost:  0.0
940 cost:  0.0
941 cost:  0.0
942 cost:  0.0
943 cost:  0.0
944 cost:  0.0
945 cost:  0.0
946 cost:  0.0
947 cost:  0.0
948 cost:  0.0
949 cost:  0.0
950 cost:  0.0
951 cost:  0.0
952 cost:  0.0
953 cost:  0.0
954 cost:  0.0
955 cost:  0.0
956 cost:  0.0
957 cost:  0.0
958 cost:  0.0
959 cost:  0.0
960 cost:  0.0
961 cost:  0.0
962 cost:  0.0
963 cost:  0.0
964 cost:  0.0
965 cost:  0.0
966 cost:  0.0
967 cost:  0.0
968 cost:  0.0
969 cost:  0.0
970 cost:  0.0
971 cost:  0.0
972 cost:  0.0
973 cost:  0.0
974 cost:  0.0
975 cost:  0.0
976 cost:  0.0
977 cost:  0.0
978 cost:  0.0
979 cost:  0.0
980 cost:  0.0
981 cost:  0.0
982 cost:  0.0
983 cost: 

In [38]:
w1.numpy(),w2.numpy()

(array([-2.0970544e-08], dtype=float32), array([1.], dtype=float32))

In [39]:
# 5시간 공부하고 5시간 출석한 학생의 점수는?
# w1*5 + w2*5 + b

w1.numpy()[0]*5 + w2.numpy()[0]*5 + b.numpy()[0]

5.999999895147278

#  MatMul ( 행렬곱 이용)

In [40]:
df = pd.read_csv('data/test.csv', header=None)
df.columns=['q1','q2','mid','final']
df.head(3)

q1  q2  mid  final
0  73  80   75    152
1  93  88   93    185
2  89  91   90    180

In [41]:
# Matmul 사요해야하지때문에 q1 q2 mid 를 n행 3열 매트릭스로

x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,[-1]].values

In [42]:
x_data.shape, y_data.shape

((25, 3), (25, 1))

In [43]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [44]:
''' 
3행 1열     
q1
w2
mid
'''
w = tf.Variable(tf.random.uniform(  [3,1] )   ) # 특성데이터갯수, label개수
b = tf.Variable(tf.random.uniform([1]) )   # [라벨개수]

In [45]:
def compute_loss():
    hx = tf.matmul(x,w) + b
    cost = tf.reduce_mean( (hx-y)**2  )
    return cost

In [46]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss,var_list=[w,b] )
    print(i,'cost: ',compute_loss().numpy())

0 cost:  890.65643
1 cost:  63.522858
2 cost:  186.84987
3 cost:  669.66034
4 cost:  942.8056
5 cost:  863.2461
6 cost:  570.85547
7 cost:  256.18173
8 cost:  58.385597
9 cost:  30.528383
10 cost:  136.34496
11 cost:  281.43524
12 cost:  372.28818
13 cost:  365.39594
14 cost:  276.11526
15 cost:  155.53223
16 cost:  59.02884
17 cost:  21.390888
18 cost:  44.694267
19 cost:  101.86555
20 cost:  153.99825
21 cost:  171.80795
22 cost:  148.73897
23 cost:  99.9901
24 cost:  51.0634
25 cost:  23.58414
26 cost:  25.239466
27 cost:  47.85817
28 cost:  73.83154
29 cost:  86.79068
30 cost:  80.1676
31 cost:  59.13341
32 cost:  35.911705
33 cost:  22.082275
34 cost:  22.373787
35 cost:  33.039745
36 cost:  45.180786
37 cost:  50.57665
38 cost:  46.3155
39 cost:  35.65039
40 cost:  25.129717
41 cost:  20.23215
42 cost:  22.26834
43 cost:  28.212944
44 cost:  33.196022
45 cost:  33.781357
46 cost:  29.875006
47 cost:  24.256489
48 cost:  20.371582
49 cost:  20.032343
50 cost:  22.50314
51 cost:  2

407 cost:  6.7077904
408 cost:  6.7004943
409 cost:  6.6932654
410 cost:  6.6861415
411 cost:  6.679077
412 cost:  6.672084
413 cost:  6.6651692
414 cost:  6.6583576
415 cost:  6.651593
416 cost:  6.6449113
417 cost:  6.638307
418 cost:  6.6317663
419 cost:  6.6252856
420 cost:  6.6189075
421 cost:  6.612572
422 cost:  6.6063175
423 cost:  6.600144
424 cost:  6.594025
425 cost:  6.5879726
426 cost:  6.581995
427 cost:  6.5760865
428 cost:  6.5702205
429 cost:  6.564436
430 cost:  6.5587187
431 cost:  6.5530715
432 cost:  6.5474677
433 cost:  6.5419374
434 cost:  6.5364623
435 cost:  6.531064
436 cost:  6.525702
437 cost:  6.5204277
438 cost:  6.515191
439 cost:  6.510028
440 cost:  6.504922
441 cost:  6.499848
442 cost:  6.4948626
443 cost:  6.489918
444 cost:  6.485027
445 cost:  6.4802036
446 cost:  6.475418
447 cost:  6.4707017
448 cost:  6.4660254
449 cost:  6.4614196
450 cost:  6.4568477
451 cost:  6.4523396
452 cost:  6.4478817
453 cost:  6.443471
454 cost:  6.439119
455 cost:  6

808 cost:  6.017242
809 cost:  6.01683
810 cost:  6.0164366
811 cost:  6.0160384
812 cost:  6.015658
813 cost:  6.0152392
814 cost:  6.0148535
815 cost:  6.014458
816 cost:  6.01407
817 cost:  6.0136566
818 cost:  6.0132656
819 cost:  6.012884
820 cost:  6.0124745
821 cost:  6.012093
822 cost:  6.0116944
823 cost:  6.0113115
824 cost:  6.0109167
825 cost:  6.010531
826 cost:  6.010144
827 cost:  6.0097346
828 cost:  6.0093474
829 cost:  6.0089664
830 cost:  6.0085645
831 cost:  6.0081935
832 cost:  6.0077977
833 cost:  6.007409
834 cost:  6.0070295
835 cost:  6.006636
836 cost:  6.0062456
837 cost:  6.005865
838 cost:  6.0054884
839 cost:  6.0050926
840 cost:  6.0046935
841 cost:  6.004321
842 cost:  6.003934
843 cost:  6.0035496
844 cost:  6.003163
845 cost:  6.0027866
846 cost:  6.002408
847 cost:  6.0020156
848 cost:  6.0016313
849 cost:  6.001251
850 cost:  6.0008593
851 cost:  6.0004883
852 cost:  6.0001025
853 cost:  5.9997215
854 cost:  5.9993377
855 cost:  5.998945
856 cost:  5

# 케라스

In [47]:
df = pd.read_csv('data/test.csv', header=None)
df.columns=['q1','q2','mid','final']
df.head(3)

q1  q2  mid  final
0  73  80   75    152
1  93  88   93    185
2  89  91   90    180

In [48]:
x_data = df.iloc[:,:-1].values #특성데이터 추출
y_data = df.iloc[:, [-1]].values

In [49]:
dense = Dense(units = 1, input_dim =3 ) # w : 3x1   b : 1   초기값
model = Sequential([dense])
model.compile(loss='mse',optimizer=Adam(0.1))
# n행 3열
h = model.fit(x_data, y_data, epochs=500) # x값을 행렬로 주어야함


Epoch 1/500
1/1 [==============================] - 0s 277ms/step - loss: 256.2633
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 84.5605
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 211.1587
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 72.0547
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 12.3677
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 86.0712
Epoch 7/500
1/1 [==============================] - 0s 3ms/step - loss: 113.7267
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 56.5048
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 10.8745
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 29.9792
Epoch 11/500
1/1 [==============================] - 0s 3ms/step - loss: 66.9440
Epoch 12/500
1/1 [==============================] - 0s 3ms/step - loss: 62.1208
Epoch 13/500
1/1 [==========================

1/1 [==============================] - 0s 3ms/step - loss: 7.8802
Epoch 105/500
1/1 [==============================] - 0s 3ms/step - loss: 7.8648
Epoch 106/500
1/1 [==============================] - 0s 3ms/step - loss: 7.8443
Epoch 107/500
1/1 [==============================] - 0s 3ms/step - loss: 7.8224
Epoch 108/500
1/1 [==============================] - 0s 2ms/step - loss: 7.8056
Epoch 109/500
1/1 [==============================] - 0s 3ms/step - loss: 7.7878
Epoch 110/500
1/1 [==============================] - 0s 2ms/step - loss: 7.7666
Epoch 111/500
1/1 [==============================] - 0s 3ms/step - loss: 7.7481
Epoch 112/500
1/1 [==============================] - 0s 4ms/step - loss: 7.7314
Epoch 113/500
1/1 [==============================] - 0s 2ms/step - loss: 7.7118
Epoch 114/500
1/1 [==============================] - 0s 3ms/step - loss: 7.6925
Epoch 115/500
1/1 [==============================] - 0s 3ms/step - loss: 7.6757
Epoch 116/500
1/1 [==============================] - 0

1/1 [==============================] - 0s 3ms/step - loss: 6.5119
Epoch 207/500
1/1 [==============================] - 0s 3ms/step - loss: 6.5041
Epoch 208/500
1/1 [==============================] - 0s 2ms/step - loss: 6.4963
Epoch 209/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4887
Epoch 210/500
1/1 [==============================] - 0s 2ms/step - loss: 6.4811
Epoch 211/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4736
Epoch 212/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4662
Epoch 213/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4589
Epoch 214/500
1/1 [==============================] - 0s 4ms/step - loss: 6.4516
Epoch 215/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4445
Epoch 216/500
1/1 [==============================] - 0s 3ms/step - loss: 6.4374
Epoch 217/500
1/1 [==============================] - 0s 4ms/step - loss: 6.4304
Epoch 218/500
1/1 [==============================] - 0

1/1 [==============================] - 0s 3ms/step - loss: 6.0532
Epoch 309/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0511
Epoch 310/500
1/1 [==============================] - 0s 2ms/step - loss: 6.0489
Epoch 311/500
1/1 [==============================] - 0s 2ms/step - loss: 6.0468
Epoch 312/500
1/1 [==============================] - 0s 2ms/step - loss: 6.0448
Epoch 313/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0427
Epoch 314/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0407
Epoch 315/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0387
Epoch 316/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0367
Epoch 317/500
1/1 [==============================] - 0s 3ms/step - loss: 6.0348
Epoch 318/500
1/1 [==============================] - 0s 2ms/step - loss: 6.0329
Epoch 319/500
1/1 [==============================] - 0s 2ms/step - loss: 6.0310
Epoch 320/500
1/1 [==============================] - 0

1/1 [==============================] - 0s 3ms/step - loss: 5.9265
Epoch 411/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9258
Epoch 412/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9251
Epoch 413/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9244
Epoch 414/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9237
Epoch 415/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9230
Epoch 416/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9224
Epoch 417/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9217
Epoch 418/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9210
Epoch 419/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9204
Epoch 420/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9198
Epoch 421/500
1/1 [==============================] - 0s 4ms/step - loss: 5.9191
Epoch 422/500
1/1 [==============================] - 0

In [50]:
w,b = dense.get_weights()
w.shape,b.shape  # w = 3행 1열

((3, 1), (1,))

In [52]:
# q1 q2 mid  80 90 90 인 사람의 최종점수
model.predict([ 
    [80,90,90]
]) 

array([[177.85141]], dtype=float32)