In [3]:
from numpy import array
from tensorflow.keras.models import Sequential    
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU

In [4]:
x = array( [[1,2,3], [2,3,4], [3,4,5], [4,5,6]] )
y = array([4,5,6,7])
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
print(x)

x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [5]:
x = x.reshape( 4,3,1 ) # ( batch size, sequence length, hidden size)
x

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [6]:
model = Sequential()
model.add( SimpleRNN(4, activation='relu', input_shape=(3,1) ) )
# model.add( Dense(units=32) )
model.add( Dense(units=1)  )
model.compile( loss='mse', optimizer='adam')
model.fit( x,y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 3s 3s/step - loss: 49.8397
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 49.6620
Epoch 3/1000
1/1 [==============================] - 0s 8ms/step - loss: 49.4783
Epoch 4/1000
1/1 [==============================] - 0s 9ms/step - loss: 49.2998
Epoch 5/1000
1/1 [==============================] - 0s 15ms/step - loss: 49.1210
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 48.9421
Epoch 7/1000
1/1 [==============================] - 0s 10ms/step - loss: 48.7578
Epoch 8/1000
1/1 [==============================] - 0s 10ms/step - loss: 48.5718
Epoch 9/1000
1/1 [==============================] - 0s 8ms/step - loss: 48.3929
Epoch 10/1000
1/1 [==============================] - 0s 12ms/step - loss: 48.2172
Epoch 11/1000
1/1 [==============================] - 0s 16ms/step - loss: 48.0381
Epoch 12/1000
1/1 [==============================] - 0s 13ms/step - loss: 47.8607
Epoch 13/1000
1/1 [============

1/1 [==============================] - 0s 12ms/step - loss: 37.2671
Epoch 102/1000
1/1 [==============================] - 0s 13ms/step - loss: 37.1796
Epoch 103/1000
1/1 [==============================] - 0s 16ms/step - loss: 37.0934
Epoch 104/1000
1/1 [==============================] - 0s 12ms/step - loss: 37.0122
Epoch 105/1000
1/1 [==============================] - 0s 12ms/step - loss: 36.9269
Epoch 106/1000
1/1 [==============================] - 0s 13ms/step - loss: 36.8402
Epoch 107/1000
1/1 [==============================] - 0s 11ms/step - loss: 36.7527
Epoch 108/1000
1/1 [==============================] - 0s 8ms/step - loss: 36.6703
Epoch 109/1000
1/1 [==============================] - 0s 13ms/step - loss: 36.5831
Epoch 110/1000
1/1 [==============================] - 0s 13ms/step - loss: 36.4995
Epoch 111/1000
1/1 [==============================] - 0s 12ms/step - loss: 36.4145
Epoch 112/1000
1/1 [==============================] - 0s 8ms/step - loss: 36.3274
Epoch 113/1000
1/1 [=

1/1 [==============================] - 0s 12ms/step - loss: 28.7674
Epoch 201/1000
1/1 [==============================] - 0s 12ms/step - loss: 28.6645
Epoch 202/1000
1/1 [==============================] - 0s 11ms/step - loss: 28.5666
Epoch 203/1000
1/1 [==============================] - 0s 12ms/step - loss: 28.4698
Epoch 204/1000
1/1 [==============================] - 0s 12ms/step - loss: 28.3696
Epoch 205/1000
1/1 [==============================] - 0s 12ms/step - loss: 28.2701
Epoch 206/1000
1/1 [==============================] - 0s 14ms/step - loss: 28.1720
Epoch 207/1000
1/1 [==============================] - 0s 11ms/step - loss: 28.0711
Epoch 208/1000
1/1 [==============================] - 0s 10ms/step - loss: 27.9670
Epoch 209/1000
1/1 [==============================] - 0s 13ms/step - loss: 27.8654
Epoch 210/1000
1/1 [==============================] - 0s 12ms/step - loss: 27.7604
Epoch 211/1000
1/1 [==============================] - 0s 15ms/step - loss: 27.6549
Epoch 212/1000
1/1 

1/1 [==============================] - 0s 14ms/step - loss: 16.0371
Epoch 300/1000
1/1 [==============================] - 0s 11ms/step - loss: 15.8871
Epoch 301/1000
1/1 [==============================] - 0s 16ms/step - loss: 15.7453
Epoch 302/1000
1/1 [==============================] - 0s 12ms/step - loss: 15.6002
Epoch 303/1000
1/1 [==============================] - 0s 13ms/step - loss: 15.4588
Epoch 304/1000
1/1 [==============================] - 0s 15ms/step - loss: 15.3106
Epoch 305/1000
1/1 [==============================] - 0s 15ms/step - loss: 15.1678
Epoch 306/1000
1/1 [==============================] - 0s 15ms/step - loss: 15.0212
Epoch 307/1000
1/1 [==============================] - 0s 16ms/step - loss: 14.8748
Epoch 308/1000
1/1 [==============================] - 0s 13ms/step - loss: 14.7315
Epoch 309/1000
1/1 [==============================] - 0s 14ms/step - loss: 14.6015
Epoch 310/1000
1/1 [==============================] - 0s 14ms/step - loss: 14.4670
Epoch 311/1000
1/1 

1/1 [==============================] - 0s 9ms/step - loss: 4.6066
Epoch 399/1000
1/1 [==============================] - 0s 13ms/step - loss: 4.5263
Epoch 400/1000
1/1 [==============================] - 0s 12ms/step - loss: 4.4423
Epoch 401/1000
1/1 [==============================] - 0s 8ms/step - loss: 4.3571
Epoch 402/1000
1/1 [==============================] - 0s 13ms/step - loss: 4.2768
Epoch 403/1000
1/1 [==============================] - 0s 9ms/step - loss: 4.1945
Epoch 404/1000
1/1 [==============================] - 0s 11ms/step - loss: 4.1158
Epoch 405/1000
1/1 [==============================] - 0s 11ms/step - loss: 4.0398
Epoch 406/1000
1/1 [==============================] - 0s 10ms/step - loss: 3.9608
Epoch 407/1000
1/1 [==============================] - 0s 7ms/step - loss: 3.8831
Epoch 408/1000
1/1 [==============================] - 0s 11ms/step - loss: 3.8021
Epoch 409/1000
1/1 [==============================] - 0s 9ms/step - loss: 3.7312
Epoch 410/1000
1/1 [================

1/1 [==============================] - 0s 10ms/step - loss: 0.3543
Epoch 499/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.3432
Epoch 500/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.3332
Epoch 501/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.3244
Epoch 502/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.3163
Epoch 503/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.3049
Epoch 504/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.2967
Epoch 505/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.2871
Epoch 506/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.2807
Epoch 507/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.2727
Epoch 508/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.2646
Epoch 509/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.2584
Epoch 510/1000
1/1 [==============

1/1 [==============================] - 0s 13ms/step - loss: 0.0738
Epoch 599/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0737
Epoch 600/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0736
Epoch 601/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0737
Epoch 602/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0736
Epoch 603/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0735
Epoch 604/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0734
Epoch 605/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0731
Epoch 606/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0725
Epoch 607/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0724
Epoch 608/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0724
Epoch 609/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0723
Epoch 610/1000
1/1 [=============

1/1 [==============================] - 0s 12ms/step - loss: 0.0655
Epoch 699/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0655
Epoch 700/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0654
Epoch 701/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0649
Epoch 702/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0649
Epoch 703/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0648
Epoch 704/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0648
Epoch 705/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0647
Epoch 706/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0647
Epoch 707/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0644
Epoch 708/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0644
Epoch 709/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0647
Epoch 710/1000
1/1 [===========

1/1 [==============================] - 0s 11ms/step - loss: 0.0589
Epoch 799/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0585
Epoch 800/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.0584
Epoch 801/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0584
Epoch 802/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.0586
Epoch 803/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0586
Epoch 804/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0586
Epoch 805/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0586
Epoch 806/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0585
Epoch 807/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.0585
Epoch 808/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0585
Epoch 809/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0584
Epoch 810/1000
1/1 [===========

1/1 [==============================] - 0s 12ms/step - loss: 0.0525
Epoch 899/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0525
Epoch 900/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0522
Epoch 901/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0521
Epoch 902/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0516
Epoch 903/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0516
Epoch 904/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0516
Epoch 905/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0516
Epoch 906/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0515
Epoch 907/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0514
Epoch 908/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0514
Epoch 909/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0518
Epoch 910/1000
1/1 [============

1/1 [==============================] - 0s 8ms/step - loss: 0.0459
Epoch 999/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0458
Epoch 1000/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0458


In [7]:
model.layers

In [8]:
model.layers[0]

```
rnn학습 weight는 3개 



```

In [9]:
rnnW =model.layers[0].get_weights()
rnnW

[array([[-0.05789113,  0.52112293,  0.2256269 ,  0.14009897]],
       dtype=float32),
 array([[ 0.6017399 , -0.35860068, -0.7111887 , -0.05937604],
        [ 0.00966235, -0.9084654 , -0.5176556 ,  1.7568698 ],
        [-0.40351444, -1.3120723 , -0.23978938,  0.03294976],
        [-0.6891966 ,  0.81889147, -0.8009479 , -0.20876016]],
       dtype=float32),
 array([ 0.        ,  0.589537  ,  0.23369901, -0.19609238], dtype=float32)]

In [10]:
rnnW[0].shape # 1행 4열

(1, 4)

In [11]:
 model.layers[0].get_weights()


[array([[-0.05789113,  0.52112293,  0.2256269 ,  0.14009897]],
       dtype=float32),
 array([[ 0.6017399 , -0.35860068, -0.7111887 , -0.05937604],
        [ 0.00966235, -0.9084654 , -0.5176556 ,  1.7568698 ],
        [-0.40351444, -1.3120723 , -0.23978938,  0.03294976],
        [-0.6891966 ,  0.81889147, -0.8009479 , -0.20876016]],
       dtype=float32),
 array([ 0.        ,  0.589537  ,  0.23369901, -0.19609238], dtype=float32)]

In [12]:
rnnW[1].shape # 4행 4열

(4, 4)

In [13]:
rnnW[2].shape # 4 

(4,)

In [14]:
# x = array( [[1,2,3], [2,3,4], [3,4,5], [4,5,6]] )
# y = array([4,5,6,7])

 
model = Sequential()
model.add( SimpleRNN(8, activation='relu', input_shape=(3,1) ) ) # 여기서 8은 셀 사이즈, simpleRNN레이어 내의 노드 개수 10
# model.add( Dense(units=32) )  
model.add( Dense(units=1)  )
model.compile( loss='mse', optimizer='adam')
model.fit( x,y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 591ms/step - loss: 19.1719
Epoch 2/1000
1/1 [==============================] - 0s 14ms/step - loss: 18.8966
Epoch 3/1000
1/1 [==============================] - 0s 13ms/step - loss: 18.6257
Epoch 4/1000
1/1 [==============================] - 0s 14ms/step - loss: 18.3531
Epoch 5/1000
1/1 [==============================] - 0s 15ms/step - loss: 18.0973
Epoch 6/1000
1/1 [==============================] - 0s 15ms/step - loss: 17.8446
Epoch 7/1000
1/1 [==============================] - 0s 13ms/step - loss: 17.5936
Epoch 8/1000
1/1 [==============================] - 0s 17ms/step - loss: 17.3545
Epoch 9/1000
1/1 [==============================] - 0s 18ms/step - loss: 17.1101
Epoch 10/1000
1/1 [==============================] - 0s 20ms/step - loss: 16.8715
Epoch 11/1000
1/1 [==============================] - 0s 13ms/step - loss: 16.6197
Epoch 12/1000
1/1 [==============================] - 0s 11ms/step - loss: 16.3865
Epoch 13/1000
1/1 [=====

1/1 [==============================] - 0s 9ms/step - loss: 1.4331
Epoch 103/1000
1/1 [==============================] - 0s 10ms/step - loss: 1.3603
Epoch 104/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.2964
Epoch 105/1000
1/1 [==============================] - 0s 8ms/step - loss: 1.2334
Epoch 106/1000
1/1 [==============================] - 0s 8ms/step - loss: 1.1716
Epoch 107/1000
1/1 [==============================] - 0s 9ms/step - loss: 1.1129
Epoch 108/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.0540
Epoch 109/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.9918
Epoch 110/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.9385
Epoch 111/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.8866
Epoch 112/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.8354
Epoch 113/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.7873
Epoch 114/1000
1/1 [===================

1/1 [==============================] - 0s 12ms/step - loss: 0.0602
Epoch 203/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0601
Epoch 204/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0601
Epoch 205/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0600
Epoch 206/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0600
Epoch 207/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0598
Epoch 208/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0598
Epoch 209/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0597
Epoch 210/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0596
Epoch 211/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0596
Epoch 212/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0595
Epoch 213/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0594
Epoch 214/1000
1/1 [===============

1/1 [==============================] - 0s 11ms/step - loss: 0.0535
Epoch 303/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0534
Epoch 304/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0533
Epoch 305/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0533
Epoch 306/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0532
Epoch 307/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0531
Epoch 308/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0530
Epoch 309/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0530
Epoch 310/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0529
Epoch 311/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0528
Epoch 312/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0528
Epoch 313/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0527
Epoch 314/1000
1/1 [============

1/1 [==============================] - 0s 9ms/step - loss: 0.0461
Epoch 403/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.0460
Epoch 404/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0460
Epoch 405/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0459
Epoch 406/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0457
Epoch 407/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0456
Epoch 408/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0455
Epoch 409/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0453
Epoch 410/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0452
Epoch 411/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0451
Epoch 412/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0450
Epoch 413/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0450
Epoch 414/1000
1/1 [====================

1/1 [==============================] - 0s 14ms/step - loss: 0.0359
Epoch 503/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0358
Epoch 504/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0358
Epoch 505/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0356
Epoch 506/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0356
Epoch 507/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0355
Epoch 508/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0355
Epoch 509/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0354
Epoch 510/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0353
Epoch 511/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0353
Epoch 512/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0352
Epoch 513/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0351
Epoch 514/1000
1/1 [===========

1/1 [==============================] - 0s 10ms/step - loss: 0.0291
Epoch 603/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0291
Epoch 604/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0290
Epoch 605/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0289
Epoch 606/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0289
Epoch 607/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0288
Epoch 608/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0288
Epoch 609/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0287
Epoch 610/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0286
Epoch 611/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0285
Epoch 612/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.0285
Epoch 613/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0284
Epoch 614/1000
1/1 [===========

1/1 [==============================] - 0s 12ms/step - loss: 0.0245
Epoch 703/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0244
Epoch 704/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0244
Epoch 705/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0243
Epoch 706/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.0243
Epoch 707/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0243
Epoch 708/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0242
Epoch 709/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0242
Epoch 710/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0241
Epoch 711/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0241
Epoch 712/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0240
Epoch 713/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0240
Epoch 714/1000
1/1 [==============

1/1 [==============================] - 0s 12ms/step - loss: 0.0203
Epoch 803/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0203
Epoch 804/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0203
Epoch 805/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.0202
Epoch 806/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0202
Epoch 807/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0202
Epoch 808/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0202
Epoch 809/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.0201
Epoch 810/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0201
Epoch 811/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.0200
Epoch 812/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0200
Epoch 813/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0199
Epoch 814/1000
1/1 [===========

1/1 [==============================] - 0s 8ms/step - loss: 0.0166
Epoch 903/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0165
Epoch 904/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0165
Epoch 905/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0164
Epoch 906/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0164
Epoch 907/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0164
Epoch 908/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0163
Epoch 909/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0163
Epoch 910/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.0162
Epoch 911/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0162
Epoch 912/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0161
Epoch 913/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.0162
Epoch 914/1000
1/1 [==================

In [15]:
rnnW = model.layers[0].get_weights()
rnnW

[array([[ 0.15485395, -0.3521049 ,  0.6667772 , -0.14349529,  0.54481655,
         -0.08915842, -0.42954147,  0.06055081]], dtype=float32),
 array([[-0.5327243 , -0.33786982,  0.47598803,  0.263892  ,  0.5369604 ,
          0.03252851,  0.18711346,  0.2556403 ],
        [-0.45411715,  0.4414678 , -0.02609482,  0.2306146 , -0.4747881 ,
          0.29379487, -0.18855041, -0.4446677 ],
        [ 0.27936313, -0.223775  ,  0.14737485,  0.05651019,  0.4568278 ,
         -0.12027169, -0.5847722 , -0.50192523],
        [-0.13901927, -0.63713014, -0.64195514,  0.14828843, -0.30627647,
         -0.09189375,  0.06063592, -0.1003937 ],
        [ 0.07467955,  0.07599641, -0.21150108,  0.12426824,  0.1773664 ,
          0.34846708, -0.57926434,  0.67488956],
        [-0.35488248,  0.16409348, -0.3504914 , -0.66433775,  0.38561878,
          0.05543818,  0.0797507 , -0.08085119],
        [-0.01502076, -0.44600815,  0.44732457, -0.5208149 , -0.40022352,
          0.32894608, -0.24594164,  0.02514027],

In [16]:
rnnW[0].shape # 1행 8열

(1, 8)

In [17]:
rnnW[1].shape # 8행 4열

(8, 8)

In [18]:
rnnW[2].shape # 8

(8,)

In [19]:
w,b = model.layers[1].get_weights()

In [20]:
w.shape

(8, 1)

In [21]:
b.shape

(1,)

In [22]:
model.predict(array([1,2,3]).reshape(1,3,1))

array([[3.822925]], dtype=float32)

# Many to Many 
----


In [23]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN,GRU,TimeDistributed

In [24]:
X = list()
Y = list()
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

In [25]:
print(X)
print('='*30)
print(Y)

[[[  5]
  [ 10]
  [ 15]]

 [[ 20]
  [ 25]
  [ 30]]

 [[ 35]
  [ 40]
  [ 45]]

 [[ 50]
  [ 55]
  [ 60]]

 [[ 65]
  [ 70]
  [ 75]]

 [[ 80]
  [ 85]
  [ 90]]

 [[ 95]
  [100]
  [105]]

 [[110]
  [115]
  [120]]

 [[125]
  [130]
  [135]]

 [[140]
  [145]
  [150]]

 [[155]
  [160]
  [165]]

 [[170]
  [175]
  [180]]

 [[185]
  [190]
  [195]]

 [[200]
  [205]
  [210]]

 [[215]
  [220]
  [225]]

 [[230]
  [235]
  [240]]

 [[245]
  [250]
  [255]]

 [[260]
  [265]
  [270]]

 [[275]
  [280]
  [285]]

 [[290]
  [295]
  [300]]]
[[[ 20]
  [ 25]
  [ 30]]

 [[ 35]
  [ 40]
  [ 45]]

 [[ 50]
  [ 55]
  [ 60]]

 [[ 65]
  [ 70]
  [ 75]]

 [[ 80]
  [ 85]
  [ 90]]

 [[ 95]
  [100]
  [105]]

 [[110]
  [115]
  [120]]

 [[125]
  [130]
  [135]]

 [[140]
  [145]
  [150]]

 [[155]
  [160]
  [165]]

 [[170]
  [175]
  [180]]

 [[185]
  [190]
  [195]]

 [[200]
  [205]
  [210]]

 [[215]
  [220]
  [225]]

 [[230]
  [235]
  [240]]

 [[245]
  [250]
  [255]]

 [[260]
  [265]
  [270]]

 [[275]
  [280]
  [285]]

 [[290]
  [2

In [26]:
X.shape,Y.shape

((20, 3, 1), (20, 3, 1))

In [27]:
X[0] # 5 10 15를 

array([[ 5],
       [10],
       [15]])

In [28]:
Y[0] # 각각 20, 25, 30 으로 예측

array([[20],
       [25],
       [30]])

TimeDistributed(Dense(1)  
- 각 스텝마다 cost (오류)를 계산해서 하위 스텝으로 오류를 전파하여 각 weight를 업데이트 RNN에선 안쓰임, LSTM에서 쓰임

In [29]:
model = Sequential() 
model.add(LSTM(64, input_shape=(3,1),activation='relu',return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(loss = 'mse',optimizer = 'adam')
model.fit(X,Y,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 979ms/step - loss: 30355.4434
Epoch 2/1000
1/1 [==============================] - 0s 33ms/step - loss: 29992.6289
Epoch 3/1000
1/1 [==============================] - 0s 32ms/step - loss: 29654.6211
Epoch 4/1000
1/1 [==============================] - 0s 25ms/step - loss: 29329.3242
Epoch 5/1000
1/1 [==============================] - 0s 31ms/step - loss: 29008.9746
Epoch 6/1000
1/1 [==============================] - 0s 31ms/step - loss: 28692.0352
Epoch 7/1000
1/1 [==============================] - 0s 33ms/step - loss: 28375.9648
Epoch 8/1000
1/1 [==============================] - 0s 30ms/step - loss: 28054.4414
Epoch 9/1000
1/1 [==============================] - 0s 28ms/step - loss: 27726.3066
Epoch 10/1000
1/1 [==============================] - 0s 27ms/step - loss: 27400.9727
Epoch 11/1000
1/1 [==============================] - 0s 32ms/step - loss: 27085.0508
Epoch 12/1000
1/1 [==============================] - 0s 28ms/step - loss:

1/1 [==============================] - 0s 19ms/step - loss: 5725.8906
Epoch 97/1000
1/1 [==============================] - 0s 26ms/step - loss: 5630.2876
Epoch 98/1000
1/1 [==============================] - 0s 19ms/step - loss: 5535.1084
Epoch 99/1000
1/1 [==============================] - 0s 20ms/step - loss: 5441.7856
Epoch 100/1000
1/1 [==============================] - 0s 20ms/step - loss: 5347.0059
Epoch 101/1000
1/1 [==============================] - 0s 23ms/step - loss: 5252.3623
Epoch 102/1000
1/1 [==============================] - 0s 21ms/step - loss: 5154.7720
Epoch 103/1000
1/1 [==============================] - 0s 15ms/step - loss: 5059.9395
Epoch 104/1000
1/1 [==============================] - 0s 18ms/step - loss: 4963.6650
Epoch 105/1000
1/1 [==============================] - 0s 17ms/step - loss: 4867.5859
Epoch 106/1000
1/1 [==============================] - 0s 17ms/step - loss: 4770.6045
Epoch 107/1000
1/1 [==============================] - 0s 20ms/step - loss: 4670.445

1/1 [==============================] - 0s 18ms/step - loss: 300.4640
Epoch 193/1000
1/1 [==============================] - 0s 16ms/step - loss: 279.7608
Epoch 194/1000
1/1 [==============================] - 0s 18ms/step - loss: 260.9628
Epoch 195/1000
1/1 [==============================] - 0s 20ms/step - loss: 244.0325
Epoch 196/1000
1/1 [==============================] - 0s 14ms/step - loss: 226.1024
Epoch 197/1000
1/1 [==============================] - 0s 21ms/step - loss: 212.7534
Epoch 198/1000
1/1 [==============================] - 0s 21ms/step - loss: 188.9465
Epoch 199/1000
1/1 [==============================] - 0s 23ms/step - loss: 184.3012
Epoch 200/1000
1/1 [==============================] - 0s 23ms/step - loss: 178.9689
Epoch 201/1000
1/1 [==============================] - 0s 20ms/step - loss: 175.9702
Epoch 202/1000
1/1 [==============================] - 0s 19ms/step - loss: 146.9351
Epoch 203/1000
1/1 [==============================] - 0s 21ms/step - loss: 126.0081
Epoch 2

1/1 [==============================] - 0s 22ms/step - loss: 27.1206
Epoch 291/1000
1/1 [==============================] - 0s 25ms/step - loss: 27.0242
Epoch 292/1000
1/1 [==============================] - 0s 18ms/step - loss: 26.9308
Epoch 293/1000
1/1 [==============================] - 0s 18ms/step - loss: 26.8155
Epoch 294/1000
1/1 [==============================] - 0s 24ms/step - loss: 26.7231
Epoch 295/1000
1/1 [==============================] - 0s 19ms/step - loss: 26.6226
Epoch 296/1000
1/1 [==============================] - 0s 15ms/step - loss: 26.5283
Epoch 297/1000
1/1 [==============================] - 0s 16ms/step - loss: 26.4397
Epoch 298/1000
1/1 [==============================] - 0s 20ms/step - loss: 26.3406
Epoch 299/1000
1/1 [==============================] - 0s 19ms/step - loss: 26.2457
Epoch 300/1000
1/1 [==============================] - 0s 13ms/step - loss: 26.1480
Epoch 301/1000
1/1 [==============================] - 0s 13ms/step - loss: 26.0503
Epoch 302/1000
1/1 

1/1 [==============================] - 0s 19ms/step - loss: 19.4123
Epoch 389/1000
1/1 [==============================] - 0s 20ms/step - loss: 19.3556
Epoch 390/1000
1/1 [==============================] - 0s 22ms/step - loss: 19.2916
Epoch 391/1000
1/1 [==============================] - 0s 17ms/step - loss: 19.2162
Epoch 392/1000
1/1 [==============================] - 0s 19ms/step - loss: 19.1669
Epoch 393/1000
1/1 [==============================] - 0s 17ms/step - loss: 19.0722
Epoch 394/1000
1/1 [==============================] - 0s 13ms/step - loss: 19.0339
Epoch 395/1000
1/1 [==============================] - 0s 17ms/step - loss: 18.9438
Epoch 396/1000
1/1 [==============================] - 0s 19ms/step - loss: 18.8994
Epoch 397/1000
1/1 [==============================] - 0s 17ms/step - loss: 18.8178
Epoch 398/1000
1/1 [==============================] - 0s 14ms/step - loss: 18.7626
Epoch 399/1000
1/1 [==============================] - 0s 15ms/step - loss: 18.6920
Epoch 400/1000
1/1 

1/1 [==============================] - 0s 21ms/step - loss: 13.9253
Epoch 487/1000
1/1 [==============================] - 0s 15ms/step - loss: 13.9755
Epoch 488/1000
1/1 [==============================] - 0s 18ms/step - loss: 13.8742
Epoch 489/1000
1/1 [==============================] - 0s 20ms/step - loss: 13.8230
Epoch 490/1000
1/1 [==============================] - 0s 17ms/step - loss: 13.8129
Epoch 491/1000
1/1 [==============================] - 0s 19ms/step - loss: 13.6955
Epoch 492/1000
1/1 [==============================] - 0s 19ms/step - loss: 13.6929
Epoch 493/1000
1/1 [==============================] - 0s 16ms/step - loss: 13.6135
Epoch 494/1000
1/1 [==============================] - 0s 17ms/step - loss: 13.5867
Epoch 495/1000
1/1 [==============================] - 0s 23ms/step - loss: 13.5486
Epoch 496/1000
1/1 [==============================] - 0s 23ms/step - loss: 13.4803
Epoch 497/1000
1/1 [==============================] - 0s 21ms/step - loss: 13.4665
Epoch 498/1000
1/1 

1/1 [==============================] - 0s 14ms/step - loss: 8.1721
Epoch 586/1000
1/1 [==============================] - 0s 18ms/step - loss: 8.0765
Epoch 587/1000
1/1 [==============================] - 0s 20ms/step - loss: 7.9786
Epoch 588/1000
1/1 [==============================] - 0s 14ms/step - loss: 7.8802
Epoch 589/1000
1/1 [==============================] - 0s 18ms/step - loss: 7.7805
Epoch 590/1000
1/1 [==============================] - 0s 20ms/step - loss: 7.6788
Epoch 591/1000
1/1 [==============================] - 0s 24ms/step - loss: 7.5818
Epoch 592/1000
1/1 [==============================] - 0s 21ms/step - loss: 7.4815
Epoch 593/1000
1/1 [==============================] - 0s 25ms/step - loss: 7.3841
Epoch 594/1000
1/1 [==============================] - 0s 29ms/step - loss: 7.2900
Epoch 595/1000
1/1 [==============================] - 0s 23ms/step - loss: 7.1955
Epoch 596/1000
1/1 [==============================] - 0s 25ms/step - loss: 7.1001
Epoch 597/1000
1/1 [===========

1/1 [==============================] - 0s 16ms/step - loss: 3.4973
Epoch 686/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.4778
Epoch 687/1000
1/1 [==============================] - 0s 18ms/step - loss: 3.4595
Epoch 688/1000
1/1 [==============================] - 0s 15ms/step - loss: 3.4408
Epoch 689/1000
1/1 [==============================] - 0s 21ms/step - loss: 3.4215
Epoch 690/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.4029
Epoch 691/1000
1/1 [==============================] - 0s 17ms/step - loss: 3.3844
Epoch 692/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.3676
Epoch 693/1000
1/1 [==============================] - 0s 17ms/step - loss: 3.3501
Epoch 694/1000
1/1 [==============================] - 0s 18ms/step - loss: 3.3317
Epoch 695/1000
1/1 [==============================] - 0s 20ms/step - loss: 3.3139
Epoch 696/1000
1/1 [==============================] - 0s 20ms/step - loss: 3.2964
Epoch 697/1000
1/1 [===========

1/1 [==============================] - 0s 25ms/step - loss: 2.2266
Epoch 786/1000
1/1 [==============================] - 0s 27ms/step - loss: 2.2192
Epoch 787/1000
1/1 [==============================] - 0s 22ms/step - loss: 2.2105
Epoch 788/1000
1/1 [==============================] - 0s 22ms/step - loss: 2.2022
Epoch 789/1000
1/1 [==============================] - 0s 24ms/step - loss: 2.1941
Epoch 790/1000
1/1 [==============================] - 0s 24ms/step - loss: 2.1851
Epoch 791/1000
1/1 [==============================] - 0s 26ms/step - loss: 2.1778
Epoch 792/1000
1/1 [==============================] - 0s 22ms/step - loss: 2.1695
Epoch 793/1000
1/1 [==============================] - 0s 27ms/step - loss: 2.1612
Epoch 794/1000
1/1 [==============================] - 0s 22ms/step - loss: 2.1535
Epoch 795/1000
1/1 [==============================] - 0s 24ms/step - loss: 2.1458
Epoch 796/1000
1/1 [==============================] - 0s 26ms/step - loss: 2.1377
Epoch 797/1000
1/1 [===========

1/1 [==============================] - 0s 20ms/step - loss: 1.6017
Epoch 886/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.5971
Epoch 887/1000
1/1 [==============================] - 0s 22ms/step - loss: 1.5925
Epoch 888/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.5879
Epoch 889/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.5838
Epoch 890/1000
1/1 [==============================] - 0s 23ms/step - loss: 1.5794
Epoch 891/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.5749
Epoch 892/1000
1/1 [==============================] - 0s 25ms/step - loss: 1.5703
Epoch 893/1000
1/1 [==============================] - 0s 22ms/step - loss: 1.5657
Epoch 894/1000
1/1 [==============================] - 0s 24ms/step - loss: 1.5618
Epoch 895/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.5569
Epoch 896/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.5524
Epoch 897/1000
1/1 [===========

1/1 [==============================] - 0s 18ms/step - loss: 1.2324
Epoch 986/1000
1/1 [==============================] - 0s 18ms/step - loss: 1.2288
Epoch 987/1000
1/1 [==============================] - 0s 17ms/step - loss: 1.2259
Epoch 988/1000
1/1 [==============================] - 0s 18ms/step - loss: 1.2230
Epoch 989/1000
1/1 [==============================] - 0s 17ms/step - loss: 1.2199
Epoch 990/1000
1/1 [==============================] - 0s 17ms/step - loss: 1.2165
Epoch 991/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.2140
Epoch 992/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.2107
Epoch 993/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.2076
Epoch 994/1000
1/1 [==============================] - 0s 18ms/step - loss: 1.2042
Epoch 995/1000
1/1 [==============================] - 0s 17ms/step - loss: 1.2019
Epoch 996/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.1985
Epoch 997/1000
1/1 [===========

In [30]:
arr = np.array([300,305,310]) 
model.predict(arr.reshape(1,3,1))
# 300 305 310의 예측값 -> 316 320 325 

array([[[315.11194],
        [319.90527],
        [325.61084]]], dtype=float32)

In [31]:
model.layers[0].get_weights()

[array([[ 3.17402184e-02, -8.83095264e-02,  1.19443312e-01,
          5.07212467e-02,  1.64321363e-02,  4.47003245e-02,
         -1.41508058e-01,  1.12816080e-01, -2.55328640e-02,
          4.04911451e-02, -9.08781067e-02,  2.19933659e-01,
         -8.20916221e-02, -4.39829268e-02,  2.89231330e-01,
          2.87904173e-01,  1.43452972e-01,  9.50353742e-02,
          6.69602573e-01, -2.38794070e-02, -1.64885566e-01,
         -5.53470626e-02,  5.37924528e-01, -3.17944959e-02,
         -1.08778045e-01,  6.59455359e-03, -1.49740174e-01,
          1.10457644e-01,  1.67972356e-01, -9.07120705e-02,
         -8.57216939e-02,  1.43616244e-01, -1.82897300e-02,
          6.44004568e-02,  3.79724056e-02,  2.53581136e-01,
         -3.64838541e-03, -1.50343522e-01,  8.20000768e-02,
         -1.00142948e-01,  5.16125560e-01, -1.12047471e-01,
          1.14542879e-01,  6.43642902e-01,  1.21764816e-01,
         -5.30627519e-02, -2.18618494e-02,  1.20843515e-01,
          1.90324977e-01,  6.77161098e-0

In [32]:
model.layers[0].get_weights()[0].shape

(1, 256)